---

pipeline: "gwas_priority"

# sample_file: "input/metadata.txt"

# Refgenie SA index Salmon: http://refgenomes.databio.org/v2/asset/mm10/salmon_sa_index/splash?tag=default
# reference: "input/reference/default"

#gencode
txome_fasta_mouse: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.transcripts.fa.gz"
genome_fasta_mouse: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/GRCm39.primary_assembly.genome.fa.gz"
gtf_mouse: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz"
